spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://micro-nbn.cvk0zbtmroit.us-west-2.rds.amazonaws.com:5432/widget_store_aws"
spring.datasource.username: "postgres_aws"
spring.datasource.password: "Finkle-456"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
